### ISSUE TITLE
Is there a way to get a Ref on a MaterialUI LeftNav Component?

### ISSUE THREAD

**Issue by railcar88** [FractalProject/Fractal#2]
This might be an enhancement request and not a bug but here is what I'm trying to do:
https://gist.github.com/railcar88/856b88d0f77ae046ffa0

My touch event goes into Header Handlers however the "leftNav" node cannot be found. Is this a bug and it should work, is there another way to gain access to the leftNav node or is there no way yet to find the material nodes?

**Comment by Krzysztof-Cieslak** [comment]
That sounds as a bug - looks like transformation from DUs array to plain JavaScript object is not working well if embedded DUs are used. Will try to fix it soon

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed, please check it and let me know.

**Comment by railcar88** [comment]
I get "TypeError: clo2 is not a function" where clo2 is derived from:
...
var onMenuClick = (function(e)
      {
        var node = Fractal__findDOMNode$Object_Object_(((c.refs)["leftNav"]));
        var clo2 = (node["toggle"]);
        var _1017;
        var ignored0 = (function(arg20)
        {
          return clo2(arg20);
        })(_1017);
      });
...

**Comment by railcar88** [comment]
Interestingly, if I change my HeaderHandlers module to this:
    module HeaderHandlers =
      let onMenuClick (c : Header) (e : Fractal.Component.SyntheticEvent) =
        c.refs.["LeftNav"]?toggle()

**Comment by railcar88** [comment]
Which is transpiled to this:
HeaderHandlers__onMenuClick$Unit_Unit_ = (function(c,e)
{
    var clo2 = (((c.refs)["leftNav"])["toggle"]);
    var _1020;
    return (function(arg20)
    {
      return clo2(arg20);
    })(_1020);
});

**Comment by Krzysztof-Cieslak** [comment]
That's actually OK. According to Material UI docs FindDOMNode call is not needed - http://material-ui.com/#/components/left-nav
